#include <stdio.h>

int main()
{
   // Reading a file using buffer
   FILE *pf = fopen("notes.txt", "r");
   char buffer[255];
   while (fgets(buffer, 255, pf) != NULL)
   {
      printf("%s\n", buffer);
   }
   fclose(pf);

   // Writing a file
   FILE *prf = fopen("test.txt", "w+");

   char text[] = "This is my autogenerated text file from code\nThis is the structure I followed.";
   if (prf == NULL)
   {
      printf("Error opening file\n");
      return 1;
   }
   fprintf(prf, "%s", text);
   printf("File was written succesfully!");
   // CRITICAL STEP: Rewind the cursor to the start!
   // Without this, the cursor is at the very end, and reads nothing.
   rewind(prf);
   char buffer_io[255];
   printf("\n--- Reading File Content ---\n");
   while (fgets(buffer_io, 255, prf) != NULL)
   {
      printf("%s", buffer_io);
   }

   fclose(prf);
   return 0;
}